language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  - DISPLAY=:1
services:
  - mongodb
before_install:
  - ./scripts/travis/write_sdConfig.sh
  - ./scripts/travis/write_seConfig.sh
  - Xvfb :1 &
install:
  - wget https://github.com/joneshf/purescript/releases/download/v0.6.1.2/linux64.tar.gz
  - sudo tar zxvf linux64.tar.gz -C /usr/local/bin purescript/psc{,i,-docs,-make} --strip-components=1
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm test
after_success:
  - ./scripts/travis/dist.sh
deploy:
  provider: releases
  api_key: $GITHUB_RELEASES_TOKEN
  file:
    - dist/SlamData/linux64.tar.gz
    - dist/SlamData/osx.zip
    - dist/SlamData/win.zip
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
