language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  - PATH=$HOME/bin:$PATH DISPLAY=:1
services:
  - mongodb
before_install:
  - mkdir -p $HOME/bin
  - ./scripts/travis/write_sdConfig.sh
  - ./scripts/travis/write_seConfig.sh
  - Xvfb :1 &
install:
  - wget https://github.com/purescript/purescript/releases/download/v0.6.1.1/linux64.tar.gz
  - tar zxvf linux64.tar.gz
  - cp purescript/psc{,i,-docs,-make} $HOME/bin
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm test
after_success:
  - ./scripts/travis/dist.sh
deploy:
  provider: releases
  api_key: $GITHUB_RELEASES_TOKEN
  file:
    - dist/SlamData/linux64.tar.gz
    - dist/SlamData/osx.zip
    - dist/SlamData/win.zip
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
