language: node_js
node_js:
  - "0.10"
notifications:
  email: false
env:
  - PATH=$HOME/bin:$PATH purescript_datadir=$HOME/.local/share/purescript DISPLAY=:1
services:
  - mongodb
before_install:
  - mkdir -p $HOME/bin
  - mkdir -p $HOME/.local/share/purescript/prelude
  - ./scripts/travis/write_sdConfig.sh
  - ./scripts/travis/write_seConfig.sh
  - Xvfb :1 &
install:
  - wget -O  $HOME/bin/linux64.tar.gz https://github.com/purescript/purescript/releases/download/v0.6.1/linux64.tar.gz
  - tar -xzf $HOME/bin/linux64.tar.gz $HOME/bin/
  - chmod a+x $HOME/bin/psc
  - chmod a+x $HOME/bin/psc-make
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm test
after_success:
  - ./scripts/travis/dist.sh
deploy:
  provider: releases
  api_key: $GITHUB_RELEASES_TOKEN
  file:
    - dist/SlamData/linux64.tar.gz
    - dist/SlamData/osx.zip
    - dist/SlamData/win.zip
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
